export const CART_ADD_FOOD = 'CART_ADD_FOOD';
export const CART_REMOVE_FOOD = 'CART_REMOVE_FOOD';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';